version: "3"
services:
  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: websockets-whatsapp-clone/client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
  backend:
    container_name: awesome_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: websockets-whatsapp-clone/server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app
